controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
easy_admin_bundle:
    resource: ../src/Controller/Admin/
    type: annotation
    prefix: /admin
api_login_check:
    path: /api/login_check